library(tidyverse)
library(rcompanion)

# Read in data as a tibble
cp = read.csv('csv/Coastal_plain_cleaned.csv')

# From http://rcompanion.org/handbook/F_15.html

pairwisePercentileTest(CM  ~ Biotic.Classification, test = 'percentile', r = 20000, tau = 0.8, data = cp)
pairwisePercentileTest(IH  ~ Biotic.Classification, test = 'percentile', r = 20000, tau = 0.8, data = cp)
pairwisePercentileTest(P  ~ Biotic.Classification, test = 'percentile', r = 20000, tau = 0.8, data = cp)
pairwisePercentileTest(BSL  ~ Biotic.Classification, test = 'percentile', r = 20000, tau = 0.8, data = cp)
pairwisePercentileTest(BSR  ~ Biotic.Classification, test = 'percentile', r = 20000, tau = 0.8, data = cp)
pairwisePercentileTest(BVL  ~ Biotic.Classification, test = 'percentile', r = 20000, tau = 0.8, data = cp)
pairwisePercentileTest(BVR  ~ Biotic.Classification, test = 'percentile', r = 20000, tau = 0.8, data = cp)
pairwisePercentileTest(S  ~ Biotic.Classification, test = 'percentile', r = 20000, tau = 0.8, data = cp)
pairwisePercentileTest(RZL  ~ Biotic.Classification, test = 'percentile', r = 20000, tau = 0.8, data = cp)
pairwisePercentileTest(RZR  ~ Biotic.Classification, test = 'percentile', r = 20000, tau = 0.8, data = cp)
pairwisePercentileTest(Alkalinity..Titrimetric..pH.4.5.  ~ Biotic.Classification, test = 'percentile', r = 20000, tau = 0.8, data = cp)
pairwisePercentileTest(Ammonia.as.N..Total  ~ Biotic.Classification, test = 'percentile', r = 20000, tau = 0.8, data = cp)
pairwisePercentileTest(BOD..20.Day..N.Inhib..CBOD20.  ~ Biotic.Classification, test = 'percentile', r = 20000, tau = 0.8, data = cp)
pairwisePercentileTest(BOD..5.Day..N.Inhib..CBOD5.  ~ Biotic.Classification, test = 'percentile', r = 20000, tau = 0.8, data = cp)
pairwisePercentileTest(Carbon..Organic...Dissolved..DOC.  ~ Biotic.Classification, test = 'percentile', r = 20000, tau = 0.8, data = cp)
pairwisePercentileTest(Carbon..Organic...Total..TOC.  ~ Biotic.Classification, test = 'percentile', r = 20000, tau = 0.8, data = cp)
pairwisePercentileTest(Chloride..Total  ~ Biotic.Classification, test = 'percentile', r = 20000, tau = 0.8, data = cp)
pairwisePercentileTest(Chlorophyll.a  ~ Biotic.Classification, test = 'percentile', r = 20000, tau = 0.8, data = cp)
pairwisePercentileTest(Conductance..Specific...Field  ~ Biotic.Classification, test = 'percentile', r = 20000, tau = 0.8, data = cp)
pairwisePercentileTest(Flow..Cubic.Feet.Per.Second  ~ Biotic.Classification, test = 'percentile', r = 20000, tau = 0.8, data = cp)
pairwisePercentileTest(Hardness.as.CaCO3  ~ Biotic.Classification, test = 'percentile', r = 20000, tau = 0.8, data = cp)
pairwisePercentileTest(Nitrate.Nitrite.as.N..Total  ~ Biotic.Classification, test = 'percentile', r = 20000, tau = 0.8, data = cp)
pairwisePercentileTest(Nitrogen..Total..Alkaline.Persulfate  ~ Biotic.Classification, test = 'percentile', r = 20000, tau = 0.8, data = cp)
pairwisePercentileTest(Orthophosphorus..Soluable  ~ Biotic.Classification, test = 'percentile', r = 20000, tau = 0.8, data = cp)
pairwisePercentileTest(Oxygen..Dissolved...Membrane.Electrode  ~ Biotic.Classification, test = 'percentile', r = 20000, tau = 0.8, data = cp)
pairwisePercentileTest(Oxygen..Dissolved...Saturation  ~ Biotic.Classification, test = 'percentile', r = 20000, tau = 0.8, data = cp)
pairwisePercentileTest(pH..Field  ~ Biotic.Classification, test = 'percentile', r = 20000, tau = 0.8, data = cp)
pairwisePercentileTest(Phosphorus..Total..Alkaline.Persulfate  ~ Biotic.Classification, test = 'percentile', r = 20000, tau = 0.8, data = cp)
pairwisePercentileTest(Residue..Nonfilterable..TSS.  ~ Biotic.Classification, test = 'percentile', r = 20000, tau = 0.8, data = cp)
pairwisePercentileTest(Salinity  ~ Biotic.Classification, test = 'percentile', r = 20000, tau = 0.8, data = cp)
pairwisePercentileTest(Temperature..Air  ~ Biotic.Classification, test = 'percentile', r = 20000, tau = 0.8, data = cp)
pairwisePercentileTest(Temperature..Water  ~ Biotic.Classification, test = 'percentile', r = 20000, tau = 0.8, data = cp)
pairwisePercentileTest(Turbidity..Nephelometric.  ~ Biotic.Classification, test = 'percentile', r = 20000, tau = 0.8, data = cp)